### ISSUE TITLE
Especificação do último commit do repositório base considerado

### ISSUE THREAD

**Issue by jonasmalacofilho** [aszasz/Manual_do_Haxe#1]
Acho importante manter isso atualizado no README.md – ou num arquivo a parte – para que seja possível verificar rapidamente e com precisão quais alterações do manual em inglês ainda precisam ser incluídas com um `git diff`.

**Comment by aszasz** [comment]
Obrigado, presumo que você esteja mais interessado em me treinar no negócio do repositório do que no assunto mesmo. Em todo caso, a informação precisa constar em cada arquivo, com qual commit do arquivo correspondente no site original estão sincronizadas. Vou colocar essa observação no README e te dar acesso irrestrito aqui.

**Comment by jonasmalacofilho** [comment]
Apesar da questão de como manter um repositório de tradução ser interessante (e ainda não cheguei a ver soluções particularmente boas), meu interesse no momento está mais em ajudá-lo a reformatar a tradução e a partir daí mantê-la atualizada.

Aproveitando, acho que criação e a manutenção desta tradução importante para motivar a escrita das seções faltantes na versão em inglês, tanto por demonstrar ainda maior demanda pelo manual como por eliminar a barreira de linguagem para certos contribuidores (apesar que isso talvez seja mais aplicável a pequenas correções do que grandes adições).

Por último, obrigado por me dar acesso de escrita ao repositório! Você sabe que estou atualmente  bastante concentrado em outro projeto, mas vou tentar colaborar aqui sempre que fizer uma pausa do trabalho principal.

**Comment by jonasmalacofilho** [comment]
Fechado por 821f3a2.
